const ADD_NUMBER = "ADD_NUMBER"
const SUB_NUMBER = "SUB_NUMBER"
const CHANGE_BANNERS = "CHANGE_BANNERS"
const CHANGE_RECOMMENDS = "CHANGE_RECOMMENDS"

export {
  ADD_NUMBER,
  SUB_NUMBER,
  CHANGE_BANNERS,
  CHANGE_RECOMMENDS
}