export const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS';
export const CHANGE_HOT_RECOMMEND = 'CHANGE_HOT_RECOMMEND';
export const CHANGE_NEW_ALBUMS = 'CHANGE_NEW_ALBUMS';
export const CHANGE_TOP_UP_LIST = 'CHANGE_TOP_UP_LIST';
export const CHANGE_TOP_NEW_LIST = 'CHANGE_TOP_NEW_LIST';
export const CHANGE_TOP_ORIGIN_LIST = 'CHANGE_TOP_ORIGIN_LIST';

export const CHANGE_SETTLE_SINGER = 'recommend/CHANGE_SETTLE_SINGER';