export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG';
export const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX';
export const CHANGE_LYRICS = 'player/CHANGE_LYRICS';
export const CHANGE_LYRIC_CURRENT_INDEX = 'player/CHANGE_LYRIC_CURRENT_INDEX';